export interface MockVideo {
    id: number,
    name: string,
    publisher: string,
    thumbnail: string,  //image url
    size: number,
    viewsCount: number,
    likesCount: number,
    commentsCount: number,
    commentObject: CommentObject,
}

export interface CommentObject{
    publisher: string,
    comment: string,
    likes:number,
}

export const MockVideos: Array<MockVideo> =[
    {
        id: 1,
        name: "Video 1",
        publisher: "User A",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 102400,
        viewsCount: 5000,
        likesCount: 250,
        commentsCount: 50,
        commentObject: {
            publisher: "User B",
            comment: "Great video!",
            likes: 15,
        },
    },
    {
        id: 2,
        name: "Video 2",
        publisher: "User C",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 81920,
        viewsCount: 7500,
        likesCount: 300,
        commentsCount: 60,
        commentObject: {
            publisher: "User D",
            comment: "Interesting content.",
            likes: 10,
        },
    },
    {
        id: 3,
        name: "Video 3",
        publisher: "User E",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 153600,
        viewsCount: 4200,
        likesCount: 210,
        commentsCount: 45,
        commentObject: {
            publisher: "User F",
            comment: "I learned a lot from this.",
            likes: 8,
        },
    },
    {
        id: 4,
        name: "Video 4",
        publisher: "User G",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 122880,
        viewsCount: 6200,
        likesCount: 280,
        commentsCount: 55,
        commentObject: {
            publisher: "User H",
            comment: "Impressive!",
            likes: 12,
        },
    },
    {
        id: 5,
        name: "Video 5",
        publisher: "User I",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 204800,
        viewsCount: 5500,
        likesCount: 275,
        commentsCount: 51,
        commentObject: {
            publisher: "User J",
            comment: "Well done!",
            likes: 20,
        },
    },
    {
        id: 6,
        name: "Video 1",
        publisher: "User A",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 102400,
        viewsCount: 5000,
        likesCount: 250,
        commentsCount: 50,
        commentObject: {
            publisher: "User B",
            comment: "Great video!",
            likes: 15,
        },
    },
    {
        id: 7,
        name: "Video 2",
        publisher: "User C",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 81920,
        viewsCount: 7500,
        likesCount: 300,
        commentsCount: 60,
        commentObject: {
            publisher: "User D",
            comment: "Interesting content.",
            likes: 10,
        },
    },
    {
        id: 8,
        name: "Video 3",
        publisher: "User E",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 153600,
        viewsCount: 4200,
        likesCount: 210,
        commentsCount: 45,
        commentObject: {
            publisher: "User F",
            comment: "I learned a lot from this.",
            likes: 8,
        },
    },
    {
        id: 9,
        name: "Video 4",
        publisher: "User G",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 122880,
        viewsCount: 6200,
        likesCount: 280,
        commentsCount: 55,
        commentObject: {
            publisher: "User H",
            comment: "Impressive!",
            likes: 12,
        },
    },
    {
        id: 10,
        name: "Video 5",
        publisher: "User I",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 204800,
        viewsCount: 5500,
        likesCount: 275,
        commentsCount: 51,
        commentObject: {
            publisher: "User J",
            comment: "Well done!",
            likes: 20,
        },
    },
    {
        id: 11,
        name: "Video 1",
        publisher: "User A",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 102400,
        viewsCount: 5000,
        likesCount: 250,
        commentsCount: 50,
        commentObject: {
            publisher: "User B",
            comment: "Great video!",
            likes: 15,
        },
    },
    {
        id: 12,
        name: "Video 2",
        publisher: "User C",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 81920,
        viewsCount: 7500,
        likesCount: 300,
        commentsCount: 60,
        commentObject: {
            publisher: "User D",
            comment: "Interesting content.",
            likes: 10,
        },
    },
    {
        id: 13,
        name: "Video 3",
        publisher: "User E",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 153600,
        viewsCount: 4200,
        likesCount: 210,
        commentsCount: 45,
        commentObject: {
            publisher: "User F",
            comment: "I learned a lot from this.",
            likes: 8,
        },
    },
    {
        id: 14,
        name: "Video 4",
        publisher: "User G",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 122880,
        viewsCount: 6200,
        likesCount: 280,
        commentsCount: 55,
        commentObject: {
            publisher: "User H",
            comment: "Impressive!",
            likes: 12,
        },
    },
    {
        id: 15,
        name: "Video 5",
        publisher: "User I",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 204800,
        viewsCount: 5500,
        likesCount: 275,
        commentsCount: 51,
        commentObject: {
            publisher: "User J",
            comment: "Well done!",
            likes: 20,
        },
    },
    {
        id: 16,
        name: "Video 1",
        publisher: "User A",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 102400,
        viewsCount: 5000,
        likesCount: 250,
        commentsCount: 50,
        commentObject: {
            publisher: "User B",
            comment: "Great video!",
            likes: 15,
        },
    },
    {
        id: 17,
        name: "Video 2",
        publisher: "User C",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 81920,
        viewsCount: 7500,
        likesCount: 300,
        commentsCount: 60,
        commentObject: {
            publisher: "User D",
            comment: "Interesting content.",
            likes: 10,
        },
    },
    {
        id: 18,
        name: "Video 3",
        publisher: "User E",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 153600,
        viewsCount: 4200,
        likesCount: 210,
        commentsCount: 45,
        commentObject: {
            publisher: "User F",
            comment: "I learned a lot from this.",
            likes: 8,
        },
    },
    {
        id: 19,
        name: "Video 4",
        publisher: "User G",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 122880,
        viewsCount: 6200,
        likesCount: 280,
        commentsCount: 55,
        commentObject: {
            publisher: "User H",
            comment: "Impressive!",
            likes: 12,
        },
    },
    {
        id: 20,
        name: "Video 5",
        publisher: "User I",
        thumbnail: "../../assets/thumbnail.jpg",
        size: 204800,
        viewsCount: 5500,
        likesCount: 275,
        commentsCount: 51,
        commentObject: {
            publisher: "User J",
            comment: "Well done!",
            likes: 20,
        },
    },
]
